### PR TITLE
Adding a few patches to poppler

### PR DESCRIPTION
**Pull request by cjordan7**

### CODE REVIEW

**Comment by hazimeh** [comment]
A quick look at B203, I think the condition is wrong. The original bug was triggered when fileSpec is not a Dict but it was used as a Dict when calculating the value of obj1.

The proper forward-porting would be to reverse the fix and add a canary just before `obj1 = fileSpec.dictLookup("Desc");`. The trigger condition would be: `fileSpec.isDict() == false` (or the equivalent using the logical negation operator: !)

Then, when fileSpec is not a Dict, the bug is recorded as triggered (by the canary), and the following line would try to use it as Dict, which is a Type Confusion bug (please change the type accordingly in the Google Sheets document).

**Comment by hazimeh** [comment]
A quick look at B203, I think the condition is wrong. The original bug was triggered when fileSpec is not a Dict but it was used as a Dict when calculating the value of obj1.

The proper forward-porting would be to reverse the fix and add a canary just before `obj1 = fileSpec.dictLookup("Desc");`. The trigger condition would be: `fileSpec.isDict() == false` (or the equivalent using the logical negation operator: !)

Then, when fileSpec is not a Dict, the bug is recorded as triggered (by the canary), and the following line would try to use it as Dict, which is a Type Confusion bug (please change the type accordingly in the Google Sheets document).

**Comment by hazimeh** [comment]
A quick look at B203, I think the condition is wrong. The original bug was triggered when fileSpec is not a Dict but it was used as a Dict when calculating the value of obj1.

The proper forward-porting would be to reverse the fix and add a canary just before `obj1 = fileSpec.dictLookup("Desc");`. The trigger condition would be: `fileSpec.isDict() == false` (or the equivalent using the logical negation operator: !)

Then, when fileSpec is not a Dict, the bug is recorded as triggered (by the canary), and the following line would try to use it as Dict, which is a Type Confusion bug (please change the type accordingly in the Google Sheets document).

**Comment by cjordan7** [comment]
Yeah you are right. I have updated the Google Sheets document and the patch as well. I have even added 2 more patches.

**Pull request merged**
