### PR TITLE
fix Dockerfile

### PR DESCRIPTION
**Pull request by vanhauser-thc**
building targets fails because 
```
ARG GROUP_ID 1000
RUN addgroup -g $(GROUP_ID) foo
```
results in addgroup -g 0 foo instead of 1000 as the ARG cannot be resolved in the system shell. as group id 0 already exists, and error is returned and docker stops building.

ARGs can only be used with docker commands, but are not resolved in the shell (what RUN does). Hence GROUP_ID etc. must be ENV instead.

### CODE REVIEW

**Comment by adrianherrera** [comment]
Thanks! I assume this means you can delete the args from [here](https://github.com/HexHive/magma/blob/v1.2/tools/captain/build.sh#L48-L49)?

**Comment by vanhauser-thc** [comment]
What you could do is ignore my pr and do 
ENV USERID $(USER_ID)
And then use $(USERID) in the RUN command and keep the flexibility

**Comment by adrianherrera** [comment]
Ok that’s a good idea! I’m happy for you to just modify the PR and then
I’ll merge :)

**Comment by vanhauser-thc** [comment]
done, I fixed another bug in the Dockerfile as well.

btw. I will send another PR that will optimize the afl++ which far from optimal plus cannot be easily updated to newer versions

**Comment by vanhauser-thc** [comment]
from my side this can be merged. it is working for my locally.

**Pull request merged**
